### ISSUE TITLE
A typo in connect.R

### ISSUE THREAD

**Issue by suensummit** [ropensci/elastic#71]
in the line https://github.com/ropensci/elastic/blob/master/R/connect.R#L95
`cat(paste('uri:      ', fun(x$base)), "\n")`
should the "uri" be replaced by "url" ?

**Comment by sckott** [comment]
@suensummit thanks for the message - Well, AFAIK a `url` is a type of `uri`, but I guess `url` is more well known - and correct in this case because what's printed there includes the protocol (`http`, or `https`) - well, both are correct in this case

I'll just can change it :smile: 

see for reference https://danielmiessler.com/study/url_vs_uri/
