### ISSUE TITLE
More details on connecting to remote ES (i.e. api.fda.gov)?

### ISSUE THREAD

**Issue by dbuijs** [ropensci/elastic#74]
Hi,

Not sure if this the right place to put this. I'm interested in getting data into R from the US FDA (open.fda.gov). They say that their API is ElasticSearch. My R session crashes or gives me an error when I try to use the elastic package to connect. 

     connect("https://api.fda.gov") 

Causes R to hang, and forces me to terminate the session. I suspect because the FDA site isn't responding to pings on port 9200. 

The following variants fail immediately with a error but no error message:

     connect("https://api.fda.gov", 443)
     connect("https://api.fda.gov", 80)
     connect("https://api.fda.gov/drug/event.json")
     connect("htps://api.fda.gov/drug/event.json", 80)
    connect("https://api.fda.gov/drug/event.json", 443)

Am I barking up the wrong tree here? Do I need to be running a local Elastic Search server to retrieve information from a remote one?

**Comment by arturom** [comment]
I just played around with the FDA API a little. It seems there is a API wrapping Elasticsearch. The R package is expecting to interact directly with the Elasticsearch API but it's not accessible. This is normal for public-facing sites for the sake of the cluster's safety since Elasticsearch doesn't provide security out of the box.

It's still a good Idea for them to mention their data is fetched using Elasticsearch because now you know how to write queries using the [Query String query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html)

**Comment by dbuijs** [comment]
Yeah, I was just figuring that out. For anyone else trying to get this data from R, it's looking like RCurl and friends are the way to go. Sorry if this was a bit off topic.

**Comment by sckott** [comment]
hi @dbuijs - thanks for the message. not the wrong place, good to hear about these use cases. 

that's right that they don't actually expose the Elasticsearch port.  This client does expect to connect to an elasticsearch server directly.
