### ISSUE TITLE
Connection settings for open.fda.gov

### ISSUE THREAD

**Issue by dbuijs** [ropensci/elastic#78]
Not sure if this is within scope, but open.fda.gov has an ElasticSearch API that only allows GET requests. 

I've been playing with `Search_uri` from this package to see if I can figure out the connection settings and the search defaults in `Search_uri` to work with it. This would be a great example to add to one of the Vignettes if we can get it working. 

    connect("https://api.fda.gov", es_port = 80)

This will throw an error because it won't respond to pings, but I'm pretty sure that's the correct connection info. The `Search_uri` settings are more complicated and I haven't figured them out yet. Here's what the FDA has documented: https://open.fda.gov/api/reference/

**Comment by sckott** [comment]
@dbuijs Good question. Like discussed in #74 - they don't expose the direct Elasticsearch server itself - which this package interacts with.  The FDA API has custom endpoints/routes and returned data is different than what Elasticsearch returns as well.  We can't realistically support APIs built on Elasticsearch that have custom routes and data blobs returned since they are an infinite set of possible configurations. Wish we could!
